In [1]:
import sqlite3
import pandas as pd

# Saving .csv to SQLite database

In [2]:
# reading .csv file saved in local and saving it as dataframe (alpha)
alpha = pd.read_csv('Alpha Roster.csv', header = 2, skipfooter=1)
alpha.head()

C:\Users\harsh.000\AppData\Local\Temp\ipykernel_19300\3896534617.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  alpha = pd.read_csv('Alpha Roster.csv', header = 2, skipfooter=1)

,FULL_NAME,SSAN,GRADE,RECORD_STATUS,ASSIGNED_PAS,ASSIGNED_PAS_CLEARTEXT,OFFICE_SYMBOL,DUTY_TITLE,DUTY_START_DATE,DOR,...,TYPE_SEC_INV,DT_SCTY_INVES_COMPL,SEC_ELIG_DT,TECH_ID,ACDU_STATUS,ANG_ROLL_INDICATOR,AFR_SECTION_ID,CIVILIAN_ART_ID,ATTACHED_PAS,FUNCTIONAL_CATEGORY
0,"DOE, JOHN",111-11-1111,MSG,10,PV1CF903,818 OPERATIONS SUPPORT SQ FF9030,OSK,OPERATIONS SUPERINTENDENT,01-JUN-2021,01-JAN-2020,...,A,28-NOV-2017,05-DEC-2017,NaN,NaN,NaN,NaN,NaN,NaN,A
1,"SMITH, ROBERT",111-11-1112,MAJ,10,PV1CF903,818 OPERATIONS SUPPORT SQ FF9030,SGXY,SPORTS PHYSICAL THERAPY FELLOW,04-JUN-2021,01-MAY-2022,...,T3,30-JAN-2019,07-FEB-2019,NaN,NaN,NaN,NaN,NaN,NaN,A
2,"BILES, JENNIFER",111-11-1113,SRA,20,PV1CF903,818 OPERATIONS SUPPORT SQ FF9030,SWMS,RADIO FREQUENCY SYS TECHNICIAN,01-NOV-2021,02-JUL-2021,...,T3,29-OCT-2018,16-NOV-2018,NaN,NaN,NaN,NaN,NaN,NaN,A
3,"CHASE, ZACH",111-11-1114,CPT,10,PV1CF903,818 OPERATIONS SUPPORT SQ FF9030,A2,"CHIEF, GP INTELLIGENCE TRAINING",13-NOV-2021,28-OCT-2020,...,A,20-FEB-2018,02-APR-2018,NaN,NaN,NaN,NaN,NaN,NaN,A
4,"BELL, REINA",111-11-1115,TSG,10,PV1CF903,818 OPERATIONS SUPPORT SQ FF9030,UTM,GROUP TRAINING MANAGER,21-SEP-2020,01-FEB-2020,...,3,15-SEP-2010,17-SEP-2010,NaN,NaN,NaN,NaN,NaN,NaN,A

In [3]:
# formatting SSAN as it will be used as unique identifier in future quering
alpha['SSAN'] = alpha.SSAN.str.replace('-', '')

In [4]:
# creating database file and connection instance
conn = sqlite3.connect('airforce.sqlite')

In [5]:
# saving dataframe to sqlite db as a table
alpha.to_sql(name='alpha', con=conn, if_exists='replace', index=False)
conn.commit()

# Reading saved tables from SQLite database

In [6]:
# reading table from saved sqlite
df = pd.read_sql_query("SELECT * from alpha", conn)
df

,FULL_NAME,SSAN,GRADE,RECORD_STATUS,ASSIGNED_PAS,ASSIGNED_PAS_CLEARTEXT,OFFICE_SYMBOL,DUTY_TITLE,DUTY_START_DATE,DOR,...,TYPE_SEC_INV,DT_SCTY_INVES_COMPL,SEC_ELIG_DT,TECH_ID,ACDU_STATUS,ANG_ROLL_INDICATOR,AFR_SECTION_ID,CIVILIAN_ART_ID,ATTACHED_PAS,FUNCTIONAL_CATEGORY
0,"DOE, JOHN",111111111,MSG,10,PV1CF903,818 OPERATIONS SUPPORT SQ FF9030,OSK,OPERATIONS SUPERINTENDENT,01-JUN-2021,01-JAN-2020,...,A,28-NOV-2017,05-DEC-2017,None,None,None,None,None,None,A
1,"SMITH, ROBERT",111111112,MAJ,10,PV1CF903,818 OPERATIONS SUPPORT SQ FF9030,SGXY,SPORTS PHYSICAL THERAPY FELLOW,04-JUN-2021,01-MAY-2022,...,T3,30-JAN-2019,07-FEB-2019,None,None,None,None,None,None,A
2,"BILES, JENNIFER",111111113,SRA,20,PV1CF903,818 OPERATIONS SUPPORT SQ FF9030,SWMS,RADIO FREQUENCY SYS TECHNICIAN,01-NOV-2021,02-JUL-2021,...,T3,29-OCT-2018,16-NOV-2018,None,None,None,None,None,None,A
3,"CHASE, ZACH",111111114,CPT,10,PV1CF903,818 OPERATIONS SUPPORT SQ FF9030,A2,"CHIEF, GP INTELLIGENCE TRAINING",13-NOV-2021,28-OCT-2020,...,A,20-FEB-2018,02-APR-2018,None,None,None,None,None,None,A
4,"BELL, REINA",111111115,TSG,10,PV1CF903,818 OPERATIONS SUPPORT SQ FF9030,UTM,GROUP TRAINING MANAGER,21-SEP-2020,01-FEB-2020,...,3,15-SEP-2010,17-SEP-2010,None,None,None,None,None,None,A
5,"FELTER, FRANCAIS",111111116,SSG,11,PV1CF903,818 OPERATIONS SUPPORT SQ FF9030,CA,"NCOIC, ARMORY OPERATIONS",01-JUN-2021,01-MAR-2019,...,T5,27-JAN-2022,14-FEB-2022,None,None,None,None,None,None,A
6,"GRANT, THOMAS",111111117,TSG,10,PV1CF903,818 OPERATIONS SUPPORT SQ FF9030,DOC,"GROUP, PPPM",01-DEC-2021,01-JAN-2020,...,T5,27-SEP-2020,19-OCT-2020,None,None,None,None,None,None,A
7,"THORNTON, THADD",111111118,LTC,10,PV1CF903,818 OPERATIONS SUPPORT SQ FF9030,CC,COMMANDER,05-JUN-2022,01-APR-2019,...,9,22-MAY-2015,04-JUN-2015,None,None,None,None,None,None,A
8,"ISSY, JOSEPH",111111119,SSG,10,PV1CF903,818 OPERATIONS SUPPORT SQ FF9030,LGRVM,GROUP VEH FLEET MGR,28-FEB-2022,01-DEC-2015,...,3,19-FEB-2010,04-MAR-2010,None,None,None,None,None,None,A
9,"HATRICK, PAT",111111120,TSG,10,PV1CF903,818 OPERATIONS SUPPORT SQ FF9030,CA,"NCOIC, CATM",24-FEB-2021,01-MAY-2021,...,3,28-JUN-2012,30-JUN-2012,None,None,None,None,None,None,A
10,"HAMILTON, STEWART",111111121,MAJ,10,PV1CF903,818 OPERATIONS SUPPORT SQ FF9030,DOF,DIRECTOR OF SUPPORT,11-MAR-2022,01-MAR-2020,...,T5,24-JUN-2019,16-AUG-2019,None,None,None,None,None,None,A
11,"STEWART, JONATHAN",111111122,SMS,11,PV1CF903,818 OPERATIONS SUPPORT SQ FF9030,JTL,SENIOR ENLISTED LEADER,10-NOV-2021,01-APR-2021,...,T5,15-JUL-2019,07-SEP-2019,None,None,None,None,None,None,A
12,"HEDWICK, TIMOTHY",111111123,LTC,11,PV1CF903,818 OPERATIONS SUPPORT SQ FF9030,DO,DIRECTOR OF OPERATIONS,30-JUN-2020,01-JAN-2021,...,5R,20-JAN-2019,08-APR-2019,None,None,None,None,None,None,A
13,"ESTEVEZ, ADAM",111111124,MSG,10,PV1CF903,818 OPERATIONS SUPPORT SQ FF9030,TARM,"SUPT, TENANT AVIATION RES MGMT",01-JUL-2021,01-JUL-2021,...,A,22-MAR-2011,28-MAR-2011,None,None,None,None,None,None,A
14,"HUNT, MICHAEL",111111125,MSG,10,PV1CF903,818 OPERATIONS SUPPORT SQ FF9030,CCV,OPS SUPERINTENDENT,01-OCT-2021,01-FEB-2020,...,3R,02-MAR-2017,11-MAR-2017,None,None,None,None,None,None,A

In [7]:
# saving and checking if .csv file converted to sql table and back is formatted correctly
df.to_csv('output.csv')